spring.application.name=SchoolVision
server.port=9090

# --- KONEKSYON MYSQL ---
spring.datasource.url=jdbc:mysql://localhost:3306/schoolvision_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=jenny2003@gmail.com
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# --- JPA / HIBERNATE ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# --- EMAIL GMAIL ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=jenny2003@gmail.com
spring.mail.password=glrc lgag vlpe qkrp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
