spring.application.name=NewShcool
server.port=${PORT:9090}

# ===== MySQL =====
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/schoolvision_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:jenny2003@gmail.com}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ===== Mail Brevo SMTP =====
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=465
spring.mail.username=${MAIL_USERNAME:aa3a67001@smtp-brevo.com}
spring.mail.password=${MAIL_PASSWORD:sODIa0LX1G7WzPdg}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp-relay.brevo.com

# ===== Stripe =====
stripe.secret.key=${STRIPE_SECRET_KEY:sk_test_51TR0W9HAXnVX0e}
stripe.public.key=${STRIPE_PUBLIC_KEY:pk_test_51TR0W9HAXnVX0eNgfjVvnoww08nWS4sAMFtA6pxN6mPb33uSdhQ8tTgwr1gz1wYOmC6fRPem5wfXkmc8YbmcuWNS00bYQ1USIz}
stripe.success.url=${STRIPE_SUCCESS_URL:http://localhost:9090/eleve/paiement/succes}
stripe.cancel.url=${STRIPE_CANCEL_URL:http://localhost:9090/eleve/paiement/annule}